// Fuente única de los casos de prueba de la Entrega 1. Sale de docs/10-catalogo-casos-v1.md
// (68 casos, mismos IDs y oráculos) más 6 casos nuevos para US-66 y US-68, que no tenían ninguno.
// Cada paso lleva su resultado esperado, como en la plantilla "TPO - TC and Defect Template".
// `feliz`: marca de "camino feliz" (columna del ejemplo TaskMaster).

export const CASOS = [
  // ---------------- ACC ----------------
  { id: 'CP-ACC-001', titulo: 'Sin sesión, la app redirige al login', funcionalidad: 'Acceso', historias: ['US-48'], trazas: 'FR-02 · NFR-13', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Alta', feliz: true, automatizable: 'V3',
    pre: ['Navegador sin sesión de Biyu (almacenamiento vacío).'], datos: [],
    pasos: [['Abrir la raíz de la app (/).', 'Redirige a /login?next=%2Fregister.'], ['Observar la pantalla.', 'Se ve el formulario "Entrar"; no se renderiza nada de /register.']] },
  { id: 'CP-ACC-002', titulo: 'Una ruta privada abierta sin sesión conserva el destino', funcionalidad: 'Acceso', historias: ['US-48'], trazas: 'FR-02 · C7', tecnica: 'Adivinación de errores', tipo: 'Negativo', prioridad: 'Alta', feliz: false, automatizable: 'Sí',
    pre: ['Sin sesión.'], datos: [],
    pasos: [['Navegar directo a /settings, sin pasar por /login.', 'Redirige a /login?next=%2Fsettings, conservando el destino original.']] },
  { id: 'CP-ACC-003', titulo: 'Crear una cuenta con email y contraseña válidos', funcionalidad: 'Registro de usuario', historias: ['US-50', 'US-51'], trazas: 'FR-01 · ADR-011', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Alta', feliz: true, automatizable: 'V3',
    pre: ['Email sin cuenta previa.'], datos: [['Email', 'nueva@test.local (uno nuevo por corrida)'], ['Contraseña', 'Clave123!']],
    pasos: [['Ir a /signup.', 'Se ve "Crear cuenta" con los criterios de contraseña.'], ['Completar email, contraseña y "Confirmar contraseña" con el mismo valor.', 'Los criterios se marcan como cumplidos; las contraseñas se ven enmascaradas.'], ['Tocar "Crear cuenta".', 'Cuenta creada con sesión activa, sin paso de confirmación por email (ADR-011); redirige a /register.']] },
  { id: 'CP-ACC-004', titulo: 'Contraseñas que no cumplen los criterios se rechazan', funcionalidad: 'Registro de usuario', historias: ['US-50', 'US-67'], trazas: 'FR-01', tecnica: 'Tabla de decisión', tipo: 'Negativo', prioridad: 'Alta', feliz: false, automatizable: 'Sí',
    pre: ['Emails sin cuenta previa.'], datos: [['(a)', 'abc1234 — 7 caracteres'], ['(b)', 'abcdefgh — solo minúsculas'], ['(c)', '12345678 — solo números'], ['(d)', 'abcd1234 — sin mayúscula ni especial'], ['(e)', 'Abcd123! — cumple los 5 criterios']],
    pasos: [['Intentar crear cuenta con (a), (b), (c) y (d).', 'Cada una se rechaza con un mensaje que dice qué criterio falta. No se crea la cuenta.'], ['Intentar crear cuenta con (e).', 'Se acepta.'], ['Variante API: POST /auth/v1/signup con (d), sin pasar por el formulario.', 'Rechazada: FR-01 pide validar también en el servidor.']] },
  { id: 'CP-ACC-005', titulo: 'No se puede crear una cuenta con un email ya registrado', funcionalidad: 'Registro de usuario', historias: ['US-50'], trazas: 'FR-01', tecnica: 'Adivinación de errores', tipo: 'Negativo', prioridad: 'Alta', feliz: false, automatizable: 'Sí',
    pre: ['Ya existe una cuenta con el email de prueba (la de CP-ACC-003).'], datos: [['Email', 'el de CP-ACC-003']],
    pasos: [['Ir a /signup y completar el formulario con ese email.', 'Los datos se cargan.'], ['Tocar "Crear cuenta".', 'Mensaje "Ya existe una cuenta con ese email". No se crea una segunda cuenta.'], ['Variante API: POST /auth/v1/signup con el mismo email.', 'Error user_already_exists / email_exists.']] },
  { id: 'CP-ACC-006', titulo: 'Credenciales inválidas en el login, sin arrastrar el error al signup', funcionalidad: 'Inicio de sesión', historias: ['US-48', 'US-50'], trazas: 'FR-01', tecnica: 'Adivinación de errores', tipo: 'Negativo', prioridad: 'Media', feliz: false, automatizable: 'Sí',
    pre: ['Email sin cuenta, o contraseña incorrecta para una que existe.'], datos: [['Email', 'noexiste@test.local']],
    pasos: [['Ir a /login, completar credenciales inválidas y tocar "Entrar".', 'Mensaje "Email o contraseña incorrectos".'], ['Sin recargar, tocar "Crear una cuenta".', 'En /signup el error anterior no aparece.']] },
  { id: 'CP-ACC-007', titulo: 'Alta sin sesión (confirmación de email activa) no entra a la app', funcionalidad: 'Registro de usuario', historias: ['US-51'], trazas: 'FR-01 · ADR-011', tecnica: 'Adivinación de errores', tipo: 'Límite', prioridad: 'Media', feliz: false, automatizable: 'No',
    pre: ['Hipotético: "Confirm email" activo en Supabase, de modo que signUp() no devuelve sesión.'], datos: [],
    pasos: [['Completar el signup con datos válidos.', 'Los datos se cargan.'], ['Enviar, con la respuesta de signup sin sesión.', 'No se redirige a una ruta protegida; se muestra "Te creamos la cuenta, pero hace falta confirmar el email antes de entrar."']] },
  { id: 'CP-ACC-008', titulo: 'Una cuenta nueva tiene el catálogo inicial sembrado', funcionalidad: 'Configuración', historias: ['US-43', 'US-51'], trazas: 'FR-04 · ADR-014', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Alta', feliz: true, automatizable: 'V3',
    pre: ['Cuenta recién creada por /signup.'], datos: [],
    pasos: [['Completar el signup.', 'La app entra a /register.'], ['Ir a Ajustes.', 'Están las 8 categorías (Comida y supermercado, Transporte, Servicios, Entretenimiento, Salud, Educación, Indumentaria, Otros) y las 5 cuentas de FR-04.']] },
  { id: 'CP-ACC-009', titulo: 'Cerrar sesión y no poder volver con "atrás"', funcionalidad: 'Cierre de sesión', historias: ['US-64'], trazas: 'FR-03', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Alta', feliz: true, automatizable: 'V3',
    pre: ['Sesión activa en /register, /dashboard o /transactions.'], datos: [],
    pasos: [['Desde cada pantalla, abrir Ajustes y tocar "Cerrar sesión".', 'La sesión se cierra y redirige a /login.'], ['Tocar "atrás" en el navegador.', 'No se recupera el acceso: cae otra vez en /login.']] },
  { id: 'CP-ACC-010', titulo: 'La sesión persiste al recargar y al reabrir el navegador', funcionalidad: 'Acceso', historias: ['US-49'], trazas: 'FR-03', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Media', feliz: true, automatizable: 'No',
    pre: ['Sesión activa.'], datos: [],
    pasos: [['Recargar la pestaña (F5).', 'Sigue en /register sin pedir login.'], ['Cerrar y reabrir el navegador en la misma URL.', 'La sesión persiste (localStorage).']] },
  { id: 'CP-ACC-011', titulo: 'Aislamiento entre usuarios en todas las tablas (par de autorización)', funcionalidad: 'Autorización', historias: ['US-48'], trazas: 'C7 · NFR-13', tecnica: 'Adivinación de errores', tipo: 'Negativo', prioridad: 'Alta', feliz: false, automatizable: 'Sí',
    pre: ['Usuarios A y B, cada uno con sus datos.'], datos: [],
    pasos: [['Con la sesión de B, consultar cada tabla filtrando por A.', 'B ve 0 filas de A en categories, accounts, fx_rates, transactions, ledger_entries, debts y subscriptions.'], ['Con el rol anon (sin sesión), consultar cada tabla.', 'permission denied (42501) en todas.']] },
  { id: 'CP-ACC-012', titulo: 'Contraseña y confirmación distintas bloquean el alta', funcionalidad: 'Registro de usuario', historias: ['US-66'], trazas: 'FR-01', tecnica: 'Adivinación de errores', tipo: 'Negativo', prioridad: 'Alta', feliz: false, automatizable: 'Sí', nuevo: true,
    pre: ['Email sin cuenta previa.'], datos: [['Contraseña', 'Clave123!'], ['Confirmar contraseña', 'Clave123?']],
    pasos: [['Ir a /signup y completar email, contraseña y una confirmación distinta.', 'Los dos campos se ven enmascarados.'], ['Tocar "Crear cuenta".', 'Mensaje "Las contraseñas no son iguales". No se crea la cuenta.']] },

  // ---------------- CFG ----------------
  { id: 'CP-CFG-001', titulo: 'Crear una categoría con nombre y color', funcionalidad: 'Categorías', historias: ['US-42'], trazas: 'FR-05', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Alta', feliz: true, automatizable: 'V3',
    pre: ['Usuario con categorías sembradas.'], datos: [['Nombre', 'Mascotas']],
    pasos: [['Ir a Ajustes, completar "Mascotas" y elegir un color de la paleta.', 'El nombre y el color quedan cargados.'], ['Tocar "Crear categoría".', 'Aparece en el listado activo con ese nombre y color.']] },
  { id: 'CP-CFG-002', titulo: 'Renombrar una categoría y cambiarle el color', funcionalidad: 'Categorías', historias: ['US-42'], trazas: 'FR-05', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Media', feliz: true, automatizable: 'V3',
    pre: ['Categoría "Comida y supermercado" activa.'], datos: [['Nombre nuevo', 'Comida']],
    pasos: [['Tocar "Editar" en "Comida y supermercado".', 'Se abre la edición en línea.'], ['Cambiar el nombre a "Comida" y el color; tocar "Guardar".', 'El listado muestra el nombre y el color nuevos, sin crear una fila nueva.']] },
  { id: 'CP-CFG-003', titulo: 'No se permiten dos categorías activas con el mismo nombre', funcionalidad: 'Categorías', historias: ['US-42'], trazas: 'FR-05', tecnica: 'Adivinación de errores', tipo: 'Negativo', prioridad: 'Media', feliz: false, automatizable: 'Sí',
    pre: ['Existe la categoría activa "Salud".'], datos: [['Nombre', 'Salud']],
    pasos: [['Intentar crear otra categoría "Salud".', 'Rechazado con "Ya existe una categoría activa con ese nombre".'], ['Variante API: insert directo a categories con el mismo nombre.', 'Error 23505 (unique_violation).']] },
  { id: 'CP-CFG-004', titulo: 'Archivar una categoría con historia', funcionalidad: 'Categorías', historias: ['US-44'], trazas: 'FR-05 · C10', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Alta', feliz: true, automatizable: 'V3',
    pre: ['"Entretenimiento" con al menos una transacción que la usa.'], datos: [['Transacción', '$8.000, nota "Cine"']],
    pasos: [['Archivar "Entretenimiento" en Ajustes.', 'Desaparece del listado activo.'], ['Abrir el registro.', 'No aparece en la grilla de categorías.'], ['Abrir la transacción histórica en Movimientos.', 'Conserva su categoría y la muestra con una marca de archivada.']] },
  { id: 'CP-CFG-005', titulo: 'Reusar el nombre de una categoría archivada', funcionalidad: 'Categorías', historias: ['US-42', 'US-44'], trazas: 'FR-05', tecnica: 'Tabla de decisión', tipo: 'Límite', prioridad: 'Baja', feliz: false, automatizable: 'Sí',
    pre: ['Categoría "Salidas" archivada y ninguna activa con ese nombre.'], datos: [['Nombre', 'Salidas']],
    pasos: [['Crear una categoría nueva "Salidas".', 'Se permite: el índice único solo cuenta las activas.']] },
  { id: 'CP-CFG-006', titulo: 'Crear una cuenta de tarjeta de crédito', funcionalidad: 'Cuentas', historias: ['US-45'], trazas: 'FR-05 · I6', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Alta', feliz: true, automatizable: 'V3',
    pre: ['Usuario con cuentas sembradas.'], datos: [['Nombre', 'Visa BBVA'], ['Tipo', 'Tarjeta de crédito'], ['Moneda', 'ARS']],
    pasos: [['En Ajustes, completar nombre, tipo y moneda; tocar "Crear cuenta".', 'Aparece con el tipo en español ("Tarjeta de crédito").'], ['En el registro, elegir esa cuenta para un gasto.', 'Se ofrece el selector de cuotas (I6).']] },
  { id: 'CP-CFG-007', titulo: 'No se permiten dos cuentas activas con el mismo nombre', funcionalidad: 'Cuentas', historias: ['US-45'], trazas: 'FR-05', tecnica: 'Adivinación de errores', tipo: 'Negativo', prioridad: 'Media', feliz: false, automatizable: 'Sí',
    pre: ['Existe la cuenta activa "Efectivo".'], datos: [['Nombre', 'Efectivo']],
    pasos: [['Intentar crear otra cuenta "Efectivo".', 'Rechazado con "Ya existe una cuenta activa con ese nombre".'], ['Variante API: insert directo a accounts.', 'Error 23505.']] },
  { id: 'CP-CFG-008', titulo: 'La siembra concurrente no duplica el catálogo', funcionalidad: 'Configuración', historias: ['US-43'], trazas: 'FR-04 · ADR-014', tecnica: 'Adivinación de errores', tipo: 'Límite', prioridad: 'Alta', feliz: false, automatizable: 'No',
    pre: ['Usuario recién creado, todavía sin sembrar.'], datos: [],
    pasos: [['Abrir /register en dos pestañas al mismo tiempo.', 'Las dos cargan el formulario.'], ['Contar categorías y cuentas del usuario.', 'Exactamente 8 y 5: sin duplicados.']] },
  { id: 'CP-CFG-009', titulo: 'Cargar y actualizar el tipo de cambio de referencia del mes', funcionalidad: 'Tipo de cambio', historias: ['US-46'], trazas: 'FR-12', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Alta', feliz: true, automatizable: 'V3',
    pre: ['El mes actual sin tipo de cambio cargado.'], datos: [['TC 1', '1250'], ['TC 2', '1300']],
    pasos: [['En Ajustes, elegir el mes actual, cargar 1250 y guardar.', 'Se crea la referencia del mes.'], ['Volver a cargar el mismo mes con 1300.', 'Se actualiza a 1300, sin duplicar la fila.']] },
  { id: 'CP-CFG-010', titulo: 'Tipo de cambio de referencia en cero o negativo', funcionalidad: 'Tipo de cambio', historias: ['US-46'], trazas: 'FR-12', tecnica: 'Valores límite', tipo: 'Límite', prioridad: 'Media', feliz: false, automatizable: 'Sí',
    pre: ['Ninguna.'], datos: [['Valores', '0 · -100 · 0,01']],
    pasos: [['Cargar 0 y después -100.', 'Rechazados con "El tipo de cambio debe ser mayor a cero".'], ['Cargar 0,01.', 'Aceptado (mínimo válido).'], ['Variante API: upsert directo a fx_rates y RPC upsert_fx_rate con 0 y -100.', 'Rechazados por la base.']] },
  { id: 'CP-CFG-011', titulo: 'Después de crear la cuenta aparece la configuración inicial', funcionalidad: 'Configuración inicial', historias: ['US-68'], trazas: 'FR-04 · FR-05', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Alta', feliz: true, automatizable: 'V3', nuevo: true,
    pre: ['Email sin cuenta previa.'], datos: [['Contraseña', 'Clave123!']],
    pasos: [['Crear una cuenta en /signup.', 'La cuenta se crea.'], ['Observar la pantalla siguiente.', 'Se muestra el setup (elementos con data-testid "setup-"), con los pasos "para qué la usás", categorías, cuentas y primer gasto.']] },
  { id: 'CP-CFG-012', titulo: 'Saltear todo el setup deja la siembra de siempre', funcionalidad: 'Configuración inicial', historias: ['US-68', 'US-43'], trazas: 'FR-04', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Media', feliz: false, automatizable: 'V3', nuevo: true,
    pre: ['Cuenta recién creada, con el setup a la vista.'], datos: [],
    pasos: [['Tocar "Saltear" en cada paso.', 'El setup termina y la app abre en Registrar.'], ['Ir a Ajustes.', 'Quedan las 8 categorías y 5 cuentas sembradas (US-43).']] },
  { id: 'CP-CFG-013', titulo: 'Destildar una categoría en el setup la archiva', funcionalidad: 'Configuración inicial', historias: ['US-68'], trazas: 'FR-05 · C10', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Media', feliz: false, automatizable: 'V3', nuevo: true,
    pre: ['Setup en el paso de categorías.'], datos: [['Categoría', 'Educación']],
    pasos: [['Destildar "Educación" y continuar.', 'Sigue el siguiente paso.'], ['Consultar las categorías del usuario.', '"Educación" queda archivada, no borrada.']] },
  { id: 'CP-CFG-014', titulo: 'La cuenta elegida como predeterminada viene preseleccionada', funcionalidad: 'Configuración inicial', historias: ['US-68', 'US-07'], trazas: 'FR-06', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Media', feliz: true, automatizable: 'V3', nuevo: true,
    pre: ['Setup en el paso de cuentas.'], datos: [['Cuenta', 'Tarjeta de débito']],
    pasos: [['Marcar "Tarjeta de débito" como predeterminada y seguir al primer gasto.', 'Se abre el registro guiado.'], ['Llegar al paso de detalles.', '"Tarjeta de débito" viene seleccionada.']] },
  { id: 'CP-CFG-015', titulo: 'El setup no reaparece y se puede reabrir desde Ajustes', funcionalidad: 'Configuración inicial', historias: ['US-68'], trazas: 'FR-04', tecnica: 'Transición de estados', tipo: 'Límite', prioridad: 'Baja', feliz: false, automatizable: 'V3', nuevo: true,
    pre: ['Setup completado o salteado.'], datos: [],
    pasos: [['Cerrar sesión y volver a entrar.', 'No aparece el setup: abre Registrar.'], ['Abrir el setup desde Ajustes.', 'Se muestra de nuevo.']] },

  // ---------------- REG ----------------
  { id: 'CP-REG-001', titulo: 'El registro es la pantalla de inicio', funcionalidad: 'Registro de transacciones', historias: ['US-01'], trazas: 'FR-06', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Alta', feliz: true, automatizable: 'V3',
    pre: ['Usuario autenticado.'], datos: [],
    pasos: [['Abrir la app (/).', 'Cae directo en /register, en el paso del monto.']] },
  { id: 'CP-REG-002', titulo: 'La fecha viene precargada con hoy', funcionalidad: 'Registro de transacciones', historias: ['US-03'], trazas: 'FR-06 · C1', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Media', feliz: true, automatizable: 'Sí',
    pre: ['Hoy = 2026-09-28 (fijado como dato, C1).'], datos: [['Monto', '1500']],
    pasos: [['Abrir /register, cargar un monto y elegir categoría.', 'Avanza al paso de detalles (ADR-024).'], ['Observar la fecha.', 'Precargada con la fecha de hoy.']] },
  { id: 'CP-REG-003', titulo: 'Tipo "gasto" y moneda ARS por defecto', funcionalidad: 'Registro de transacciones', historias: ['US-04', 'US-05'], trazas: 'FR-06', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Baja', feliz: true, automatizable: 'Sí',
    pre: ['Formulario recién abierto.'], datos: [],
    pasos: [['Observar tipo y moneda.', 'Tipo = Gasto; moneda = ARS; no se muestra tipo de cambio.']] },
  { id: 'CP-REG-004', titulo: 'Elegir la categoría tocando un chip', funcionalidad: 'Registro de transacciones', historias: ['US-06'], trazas: 'FR-06 · I8', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Media', feliz: true, automatizable: 'Sí',
    pre: ['Categorías activas sembradas.'], datos: [['Monto', '2300'], ['Categoría', 'Transporte']],
    pasos: [['Cargar un monto y tocar Siguiente.', 'Se ve la grilla de categorías, sin ningún select.'], ['Tocar el chip "Transporte".', 'Avanza solo al paso de detalles.'], ['Guardar.', 'La transacción queda con la categoría "Transporte".']] },
  { id: 'CP-REG-005', titulo: 'Una categoría archivada no se ofrece ni se acepta por API', funcionalidad: 'Registro de transacciones', historias: ['US-06'], trazas: 'FR-06', tecnica: 'Adivinación de errores', tipo: 'Negativo', prioridad: 'Media', feliz: false, automatizable: 'Sí',
    pre: ['Categoría "Salidas" archivada.'], datos: [],
    pasos: [['Abrir /register, cargar un monto y tocar Siguiente.', 'La grilla no muestra "Salidas".'], ['Variante API: create_transaction con el id de "Salidas".', 'Rechazado: "la categoría no existe, no es tuya o está archivada".']] },
  { id: 'CP-REG-006', titulo: 'La cuenta viene precargada con la última usada', funcionalidad: 'Registro de transacciones', historias: ['US-07'], trazas: 'FR-06', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Baja', feliz: true, automatizable: 'Sí',
    pre: ['La última transacción se guardó con "Visa BBVA".'], datos: [],
    pasos: [['Volver a abrir /register y avanzar hasta detalles.', '"Visa BBVA" viene seleccionada.']] },
  { id: 'CP-REG-007', titulo: 'Guardar sin nota', funcionalidad: 'Registro de transacciones', historias: ['US-08'], trazas: 'FR-06', tecnica: 'Valores límite', tipo: 'Límite', prioridad: 'Baja', feliz: false, automatizable: 'Sí',
    pre: ['Formulario completo salvo la nota.'], datos: [['Monto', '1234']],
    pasos: [['Dejar la nota vacía y guardar.', 'Se guarda sin error, con description = null.']] },
  { id: 'CP-REG-008', titulo: 'Fecha de ayer sí, fecha de mañana no', funcionalidad: 'Registro de transacciones', historias: ['US-09'], trazas: 'FR-06', tecnica: 'Valores límite', tipo: 'Límite', prioridad: 'Media', feliz: false, automatizable: 'Sí',
    pre: ['Hoy = 2026-09-28.'], datos: [['Ayer', '2026-09-27'], ['Mañana', '2026-09-29']],
    pasos: [['Cargar un gasto con fecha de ayer.', 'Se guarda.'], ['Cargar un gasto con fecha de mañana.', 'Rechazado: "La fecha no puede ser futura".'], ['Variante API: create_transaction con fecha futura.', 'Rechazado también en el servidor.']] },
  { id: 'CP-REG-009', titulo: 'Confirmación y formulario limpio después de guardar', funcionalidad: 'Registro de transacciones', historias: ['US-10'], trazas: 'FR-06', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Media', feliz: true, automatizable: 'Sí',
    pre: ['Formulario completo.'], datos: [['Monto', '4500']],
    pasos: [['Guardar.', 'Confirmación breve ("Gasto guardado").'], ['Observar el formulario.', 'Vuelve al paso del monto, vacío, conservando la última cuenta usada.']] },
  { id: 'CP-REG-010', titulo: 'Monto vacío, cero o negativo no se guarda', funcionalidad: 'Registro de transacciones', historias: ['US-11'], trazas: 'FR-06 · I4 · C6', tecnica: 'Valores límite', tipo: 'Negativo', prioridad: 'Alta', feliz: false, automatizable: 'Sí',
    pre: ['Ninguna.'], datos: [['Montos', 'vacío · 0 · -500 · 0,01']],
    pasos: [['Dejar el monto vacío; después 0; después -500.', 'Siguiente queda deshabilitado; no se emite ninguna escritura.'], ['Cargar 0,01 y completar.', 'Se acepta (mínimo válido).'], ['Variante API: create_transaction con 0 o negativo.', 'Rechazado con 23514 "I4: el monto debe ser mayor a cero".']] },
  { id: 'CP-REG-011', titulo: 'Monto con tres decimales', funcionalidad: 'Registro de transacciones', historias: ['US-11'], trazas: 'FR-06 · I4', tecnica: 'Valores límite', tipo: 'Límite', prioridad: 'Media', feliz: false, automatizable: 'Sí',
    pre: ['Ninguna.'], datos: [['Monto', '100,999']],
    pasos: [['Cargar 100,999.', 'Rechazado en cliente: "El monto admite hasta 2 decimales".']] },
  { id: 'CP-REG-012', titulo: 'Eliminar una transacción la saca del total del mes', funcionalidad: 'Baja lógica', historias: ['US-65'], trazas: 'FR-08 · C10 · I10', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Alta', feliz: true, automatizable: 'V3',
    pre: ['Transacción de $50.000 ARS en el mes actual, sin cuotas.'], datos: [['Nota', 'Campera']],
    pasos: [['Eliminarla desde Movimientos y confirmar el aviso.', 'Se cierra el diálogo.'], ['Ver el Resumen del mes.', 'El total ya no la incluye (I10).'], ['Consultar la base.', 'deleted_at completado: la transacción sigue existiendo, marcada como eliminada.']] },
  { id: 'CP-REG-013', titulo: 'Eliminar una compra con cuotas en meses cerrados avisa y es retroactivo', funcionalidad: 'Baja lógica', historias: ['US-65', 'US-18'], trazas: 'FR-08 · C10 · I10', tecnica: 'Adivinación de errores', tipo: 'Límite', prioridad: 'Alta', feliz: false, automatizable: 'V3',
    pre: ['Compra de $120.000 en 12 cuotas registrada el 2026-08-15.', 'Hoy = 2026-10-15 (agosto y septiembre cerrados).'], datos: [],
    pasos: [['Eliminar la compra desde octubre.', 'Antes de confirmar, avisa que cambian los totales de meses cerrados (2026-08 y 2026-09).'], ['Confirmar y ver el Resumen de agosto y de septiembre.', 'Todas las imputaciones dejan de contar, también las de meses cerrados.']] },
  { id: 'CP-REG-014', titulo: 'Otro usuario no puede leer ni borrar una transacción ajena', funcionalidad: 'Autorización', historias: ['US-48'], trazas: 'C7', tecnica: 'Adivinación de errores', tipo: 'Negativo', prioridad: 'Alta', feliz: false, automatizable: 'Sí',
    pre: ['Transacción de A.'], datos: [],
    pasos: [['Con la sesión de B, leer esa transacción por id.', '0 filas.'], ['Con la sesión de B, intentar eliminarla.', 'No la encuentra; la transacción de A queda intacta.']] },
  { id: 'CP-REG-015', titulo: 'No se puede escribir en transactions salteando la RPC', funcionalidad: 'Autorización', historias: ['US-11'], trazas: 'C4 · I1 · I1\'', tecnica: 'Adivinación de errores', tipo: 'Negativo', prioridad: 'Alta', feliz: false, automatizable: 'Sí',
    pre: ['Ninguna.'], datos: [],
    pasos: [['Intentar un insert directo a transactions (y a ledger_entries).', 'permission denied (42501): toda escritura pasa por create_transaction (C4).']] },
  { id: 'CP-REG-016', titulo: 'El monto toma el foco con teclado numérico', funcionalidad: 'Registro de transacciones', historias: ['US-02'], trazas: 'FR-06 · NFR-07', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Media', feliz: true, automatizable: 'No',
    pre: ['Ninguna.'], datos: [],
    pasos: [['Abrir /register en un celular (o emulación táctil) sin tocar nada.', 'El monto ya tiene el foco y el teclado numérico está abierto.']] },

  // ---------------- CUO ----------------
  { id: 'CP-CUO-001', titulo: 'Compra en 12 cuotas genera 12 imputaciones consecutivas', funcionalidad: 'Cuotas', historias: ['US-12'], trazas: 'FR-09 · I2 · I3', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Alta', feliz: true, automatizable: 'V3',
    pre: ['Cuenta "Visa BBVA" de tipo tarjeta de crédito.'], datos: [['Monto', '$120.000'], ['Cuotas', '12']],
    pasos: [['Elegir la cuenta, 12 cuotas y guardar $120.000.', 'Se guarda.'], ['Consultar las imputaciones.', '12 imputaciones numeradas 1 a 12, en meses consecutivos desde el de la compra.']] },
  { id: 'CP-CUO-002', titulo: 'Previsualización del impacto mensual antes de guardar', funcionalidad: 'Cuotas', historias: ['US-13'], trazas: 'FR-09', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Alta', feliz: true, automatizable: 'No',
    pre: ['Gasto de $120.000 en 12 cuotas con fecha 2026-08-15.'], datos: [],
    pasos: [['Completar el formulario sin guardar.', 'Muestra "12 cuotas de $10.000 — de 2026-08 a 2027-07" antes de tocar Guardar.']] },
  { id: 'CP-CUO-003', titulo: 'Cambiar a una cuenta que no es crédito resetea las cuotas', funcionalidad: 'Cuotas', historias: ['US-14'], trazas: 'I6', tecnica: 'Tabla de decisión', tipo: 'Negativo', prioridad: 'Alta', feliz: false, automatizable: 'Sí',
    pre: ['6 cuotas elegidas con "Visa BBVA".'], datos: [],
    pasos: [['Cambiar la cuenta a "Efectivo".', 'El selector de cuotas desaparece, el valor vuelve a 1 y hay un aviso.'], ['Variante API: create_transaction con 6 cuotas y cuenta cash.', 'Rechazado por I6.']] },
  { id: 'CP-CUO-004', titulo: 'División exacta: 12 cuotas iguales', funcionalidad: 'Cuotas', historias: ['US-15'], trazas: 'FR-10 · FR-11 · I1 · I1\' · C3', tecnica: 'Valores límite', tipo: 'Positivo', prioridad: 'Alta', feliz: true, automatizable: 'V3',
    pre: ['Ninguna.'], datos: [['Monto', '$120.000 en 12 cuotas']],
    pasos: [['Guardar $120.000 en 12 cuotas.', '12 imputaciones de exactamente $10.000; suma $120.000,00 (I1).']] },
  { id: 'CP-CUO-005', titulo: 'El resto lo absorbe la última cuota', funcionalidad: 'Cuotas', historias: ['US-15'], trazas: 'FR-10 · FR-11 · I1 · C3', tecnica: 'Valores límite', tipo: 'Límite', prioridad: 'Alta', feliz: false, automatizable: 'V3',
    pre: ['Ninguna.'], datos: [['Monto', '$100.000 en 3 cuotas']],
    pasos: [['Guardar $100.000 en 3 cuotas.', '$33.333,33 + $33.333,33 + $33.333,34 = $100.000,00. El resto va en la última.']] },
  { id: 'CP-CUO-006', titulo: 'Cantidad de cuotas: 0, 1, 2, 12 y 13', funcionalidad: 'Cuotas', historias: ['US-15', 'US-12'], trazas: 'FR-09', tecnica: 'Tabla de decisión', tipo: 'Límite', prioridad: 'Alta', feliz: false, automatizable: 'Sí',
    pre: ['Cuenta de tarjeta de crédito.'], datos: [['Cuotas', '0 · 1 · 2 · 12 · 13']],
    pasos: [['Intentar guardar con cada cantidad.', '0 rechazado; 1, 2 y 12 aceptados; 13 rechazado.']] },
  { id: 'CP-CUO-007', titulo: 'El Resumen separa las cuotas de meses anteriores', funcionalidad: 'Cuotas', historias: ['US-16'], trazas: 'FR-20', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Media', feliz: true, automatizable: 'V3',
    pre: ['Gasto de $120.000 en 12 cuotas registrado en 2026-08.'], datos: [],
    pasos: [['Ir al Resumen de 2026-09.', 'El total incluye $10.000 y "Cuotas de meses anteriores" muestra $10.000.']] },
  { id: 'CP-CUO-008', titulo: 'El listado muestra el número de cuota', funcionalidad: 'Cuotas', historias: ['US-17'], trazas: 'FR-20', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Baja', feliz: true, automatizable: 'Sí',
    pre: ['Compra en 12 cuotas de agosto; mes con la cuota 3.'], datos: [],
    pasos: [['Ver Movimientos de ese mes.', 'Muestra "3/12" junto a la imputación.']] },
  { id: 'CP-CUO-009', titulo: 'Borrar una compra en cuotas saca todas sus cuotas', funcionalidad: 'Cuotas', historias: ['US-18'], trazas: 'FR-08 · I10', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Alta', feliz: true, automatizable: 'V3',
    pre: ['Compra de $120.000 en 12 cuotas.'], datos: [],
    pasos: [['Eliminar la compra (no existe la opción de borrar una cuota suelta).', 'Las 12 imputaciones dejan de contar en todos los meses, incluidas las futuras.']] },
  { id: 'CP-CUO-010', titulo: 'En USD, la suma en pesos de las cuotas es exacta', funcionalidad: 'Cuotas', historias: ['US-15'], trazas: 'C2 · I1\'', tecnica: 'Adivinación de errores', tipo: 'Límite', prioridad: 'Media', feliz: false, automatizable: 'Sí',
    pre: ['Gasto de USD 100 en 3 cuotas con TC 1250,5555.'], datos: [],
    pasos: [['Guardar.', 'Se guarda.'], ['Sumar amount_ars de las 3 imputaciones.', 'Es exactamente transactions.amount_ars (I1\'), sin diferencias de un centavo.']] },
  { id: 'CP-CUO-011', titulo: 'Otro usuario no ve las cuotas de una compra ajena', funcionalidad: 'Autorización', historias: ['US-48'], trazas: 'C7', tecnica: 'Adivinación de errores', tipo: 'Negativo', prioridad: 'Alta', feliz: false, automatizable: 'Sí',
    pre: ['Compra en cuotas de A.'], datos: [],
    pasos: [['Con la sesión de B, consultar ledger_entries de esa compra.', '0 filas.']] },
  { id: 'CP-CUO-012', titulo: 'Un ingreso no admite cuotas aunque la cuenta sea crédito', funcionalidad: 'Cuotas', historias: ['US-12', 'US-14'], trazas: 'I6', tecnica: 'Tabla de decisión', tipo: 'Negativo', prioridad: 'Alta', feliz: false, automatizable: 'Sí',
    pre: ['Cuenta "Visa BBVA" de crédito.'], datos: [],
    pasos: [['Cargar un ingreso con esa cuenta.', 'No aparece el selector de cuotas.'], ['Variante API: ingreso en 3 cuotas con cuenta de crédito.', 'Rechazado por I6.']] },
  { id: 'CP-CUO-013', titulo: 'Un fallo a mitad de create_transaction no deja datos parciales', funcionalidad: 'Cuotas', historias: ['US-15'], trazas: 'C4 · I1 · I1\'', tecnica: 'Adivinación de errores', tipo: 'Negativo', prioridad: 'Alta', feliz: false, automatizable: 'Sí',
    pre: ['Ninguna.'], datos: [['Llamada', '$0,02 en 3 cuotas (la cuota base da 0)']],
    pasos: [['Forzar que create_transaction falle después de insertar la transacción.', 'La llamada devuelve error.'], ['Contar filas de transactions y ledger_entries.', 'Cero filas nuevas en ambas: todo se revierte (C4).']] },

  // ---------------- MON ----------------
  { id: 'CP-MON-001', titulo: 'Gasto en USD con el tipo de cambio sugerido', funcionalidad: 'Monedas', historias: ['US-19'], trazas: 'FR-12 · I5', tecnica: 'Tabla de decisión', tipo: 'Positivo', prioridad: 'Alta', feliz: true, automatizable: 'V3',
    pre: ['TC de referencia del mes = 1250.'], datos: [['Monto', 'USD 100']],
    pasos: [['Elegir USD, monto 100 y guardar sin tocar el tipo de cambio.', 'Se guarda con fx_rate = 1250 y amount_ars = 125.000.']] },
  { id: 'CP-MON-002', titulo: 'Tabla de decisión de moneda y tipo de cambio (6 filas)', funcionalidad: 'Monedas', historias: ['US-19'], trazas: 'FR-12 · I5', tecnica: 'Tabla de decisión', tipo: 'Negativo', prioridad: 'Alta', feliz: false, automatizable: 'Sí',
    pre: ['Ninguna (se ejecuta primero sin referencia del mes y después con 1250).'], datos: [['Filas', 'ARS sin TC · ARS con TC · USD con referencia sin override · USD con referencia con override · USD sin referencia sin TC · USD sin referencia con TC']],
    pasos: [['Ejecutar las seis combinaciones de 07-plan-de-testing.md §3.', 'Se guardan las filas 1, 3, 4 y 6. Se rechazan la 2 (ARS con TC, I5) y la 5 (USD sin ningún TC, con mensaje que pide el tipo de cambio).'], ['Variante API: filas 2 y 5 contra create_transaction.', 'Mismo rechazo (I5).']] },
  { id: 'CP-MON-003', titulo: 'Pisar el tipo de cambio sugerido', funcionalidad: 'Monedas', historias: ['US-20', 'US-21'], trazas: 'FR-12', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Media', feliz: true, automatizable: 'Sí',
    pre: ['TC de referencia del mes = 1250.'], datos: [['TC propio', '1300']],
    pasos: [['Elegir USD.', 'El campo sugiere 1250.'], ['Pisarlo con 1300 y guardar.', 'Se guarda con fx_rate = 1300.']] },
  { id: 'CP-MON-004', titulo: 'Cambiar la referencia no altera lo ya guardado', funcionalidad: 'Monedas', historias: ['US-22'], trazas: 'C5 · ADR-002', tecnica: 'Adivinación de errores', tipo: 'Positivo', prioridad: 'Alta', feliz: false, automatizable: 'V3',
    pre: ['Gasto de USD 100 guardado con fx_rate = 1250 (amount_ars = 125.000).'], datos: [['Nueva referencia', '1400']],
    pasos: [['Cambiar en Ajustes la referencia del mes a 1400.', 'Se guarda.'], ['Ver esa transacción y el Resumen del mes.', 'La transacción sigue valiendo $125.000; el total no cambia.']] },
  { id: 'CP-MON-005', titulo: 'El total del mes en pesos incluye lo gastado en dólares', funcionalidad: 'Monedas', historias: ['US-23'], trazas: 'FR-20 · I1\'', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Alta', feliz: true, automatizable: 'V3',
    pre: ['Un gasto de $50.000 ARS y uno de USD 100 a 1250 en el mismo mes.'], datos: [],
    pasos: [['Ver el total del mes en el Resumen.', '$175.000 ($50.000 + $125.000).']] },
  { id: 'CP-MON-006', titulo: 'El gasto en dólares se ve por separado', funcionalidad: 'Monedas', historias: ['US-24'], trazas: 'FR-20', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Baja', feliz: true, automatizable: 'Sí',
    pre: ['Gasto de USD 100 en el mes.'], datos: [],
    pasos: [['Ver el Resumen.', 'Muestra "USD 100" por separado del total en ARS.']] },
  { id: 'CP-MON-007', titulo: 'Otro usuario no lee ni modifica el tipo de cambio ajeno', funcionalidad: 'Autorización', historias: ['US-48'], trazas: 'C7', tecnica: 'Adivinación de errores', tipo: 'Negativo', prioridad: 'Alta', feliz: false, automatizable: 'Sí',
    pre: ['fx_rates de A para el mes actual.'], datos: [],
    pasos: [['Con la sesión de B, leer y actualizar esa fila.', '0 filas al leer; el update afecta 0 filas.']] },

  // ---------------- DAS ----------------
  { id: 'CP-DAS-001', titulo: 'El Resumen abre en el mes actual con su total', funcionalidad: 'Dashboard', historias: ['US-25'], trazas: 'FR-20 · I10', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Alta', feliz: true, automatizable: 'V3',
    pre: ['Transacciones en el mes actual.'], datos: [],
    pasos: [['Entrar a /dashboard sin tocar el selector de mes.', 'Muestra el total gastado del mes actual.']] },
  { id: 'CP-DAS-002', titulo: 'El mes elegido vive en la URL', funcionalidad: 'Dashboard', historias: ['US-26'], trazas: 'FR-21 · C11', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Alta', feliz: true, automatizable: 'Sí',
    pre: ['En /dashboard?period=2026-09.'], datos: [],
    pasos: [['Tocar "→" dos veces.', 'La URL pasa a period=2026-11.']] },
  { id: 'CP-DAS-003', titulo: 'Período inválido o ausente cae al mes actual', funcionalidad: 'Dashboard', historias: ['US-26'], trazas: 'C11', tecnica: 'Adivinación de errores', tipo: 'Límite', prioridad: 'Media', feliz: false, automatizable: 'Sí',
    pre: ['Ninguna.'], datos: [],
    pasos: [['Abrir /dashboard?period=fecha-invalida.', 'Cae al mes actual sin error visible y corrige la URL.'], ['Abrir /dashboard sin parámetro.', 'Ídem.']] },
  { id: 'CP-DAS-004', titulo: 'Gasto por categoría en barras', funcionalidad: 'Dashboard', historias: ['US-27'], trazas: 'FR-20', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Media', feliz: true, automatizable: 'Sí',
    pre: ['Gastos en 3 categorías: Salud $70.000, Comida $50.000, Transporte $30.000.'], datos: [],
    pasos: [['Ver el gráfico por categoría.', 'Una barra por categoría con su total, ordenadas de mayor a menor.']] },
  { id: 'CP-DAS-005', titulo: 'Gasto por cuenta', funcionalidad: 'Dashboard', historias: ['US-28'], trazas: 'FR-20', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Media', feliz: true, automatizable: 'Sí',
    pre: ['Gastos en 2 cuentas (Efectivo $120.000, Tarjeta de débito $30.000).'], datos: [],
    pasos: [['Ver el desglose por cuenta.', 'Cada total coincide con la suma manual de sus transacciones.']] },
  { id: 'CP-DAS-006', titulo: 'Ingresos y balance positivo', funcionalidad: 'Dashboard', historias: ['US-29'], trazas: 'FR-20', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Media', feliz: true, automatizable: 'Sí',
    pre: ['Ingresos $200.000 y gastos $150.000 en el mes.'], datos: [],
    pasos: [['Ver ingresos y balance.', 'Ingresos $200.000; balance +$50.000.']] },
  { id: 'CP-DAS-007', titulo: 'Balance negativo con signo explícito', funcionalidad: 'Dashboard', historias: ['US-29'], trazas: 'FR-20', tecnica: 'Valores límite', tipo: 'Límite', prioridad: 'Baja', feliz: false, automatizable: 'Sí',
    pre: ['Gastos $200.000 e ingresos $50.000.'], datos: [],
    pasos: [['Ver el balance.', '-$150.000, con signo negativo explícito.']] },
  { id: 'CP-DAS-008', titulo: 'Últimos 10 movimientos con acceso a la lista completa', funcionalidad: 'Dashboard', historias: ['US-31'], trazas: 'FR-20', tecnica: 'Caso de uso', tipo: 'Positivo', prioridad: 'Media', feliz: true, automatizable: 'Sí',
    pre: ['15 transacciones en el mes.'], datos: [],
    pasos: [['Ver "Últimos movimientos".', 'Muestra 10.'], ['Tocar "Ver todos".', 'Abre Movimientos del mes con las 15.']] },
  { id: 'CP-DAS-009', titulo: 'Una cuota heredada no cuenta como día con registro', funcionalidad: 'Dashboard', historias: ['US-32'], trazas: 'FR-20', tecnica: 'Adivinación de errores', tipo: 'Límite', prioridad: 'Baja', feliz: false, automatizable: 'Sí',
    pre: ['Compra en 12 cuotas de agosto; en diciembre solo cae su cuota.'], datos: [],
    pasos: [['Ver "días con registro" en el Resumen de diciembre.', '0 días.']] },
  { id: 'CP-DAS-010', titulo: 'Mes sin datos: estado vacío con acceso al registro', funcionalidad: 'Dashboard', historias: ['US-33'], trazas: 'FR-20', tecnica: 'Caso de uso', tipo: 'Límite', prioridad: 'Media', feliz: false, automatizable: 'Sí',
    pre: ['Mes sin ninguna transacción.'], datos: [],
    pasos: [['Ir al Resumen de ese mes.', 'Mensaje claro y un botón a /register, no un dashboard de ceros.']] },
  { id: 'CP-DAS-011', titulo: 'El Resumen de un usuario nunca muestra datos de otro', funcionalidad: 'Autorización', historias: ['US-48'], trazas: 'C7', tecnica: 'Adivinación de errores', tipo: 'Negativo', prioridad: 'Alta', feliz: false, automatizable: 'Sí',
    pre: ['Resumen de A con datos.'], datos: [],
    pasos: [['Con la sesión de B, repetir las consultas del Resumen filtrando por A.', '0 filas.']] },
]
